#!/bin/bash
#BSUB -J MHCf # Job name
#BSUB -P acc_nkcancer # allocation account or Unix group
#BSUB -q premium # queue
#BSUB -R span[hosts=1] # one node
#BSUB -n 1 # number of compute cores
#BSUB -W 40:00 # walltime in HH:MM
#BSUB -R rusage[mem=45000] # mb memory requested
#BSUB -o %J.stdout # output log (%J : JobID)
#BSUB -eo %J.stderr # error log
#BSUB -L /bin/bash # Initialize the execution environment
#

set -e
set -x

echo "Subsequent stderr output redirected to stdout" >&2
exec 2>&1

export TMPDIR=/local/JOBS/mhcflurry
export PATH=$HOME/.conda/envs/py36b/bin/:$PATH
export PYTHONUNBUFFERED=1
export KMP_SETTINGS=1

free -m
module list
env

cd /hpc/users/odonnt02/mhcflurry-scratch/20200609/mhcflurry-downloads-generation/models_class1_presentation
time mhcflurry-class1-train-presentation-models --data /hpc/users/odonnt02/mhcflurry-scratch/20200609/mhcflurry-downloads-generation/models_class1_presentation/train_data.csv.bz2 --affinity-predictor "/hpc/users/odonnt02/.local/share/mhcflurry/4/1.7.0/models_class1_pan//models.combined" --processing-predictor-with-flanks "/hpc/users/odonnt02/.local/share/mhcflurry/4/1.7.0/models_class1_processing//models.selected.short_flanks" --processing-predictor-without-flanks "/hpc/users/odonnt02/.local/share/mhcflurry/4/1.7.0/models_class1_processing//models.selected.no_flank" --out-models-dir /hpc/users/odonnt02/mhcflurry-scratch/20200609/mhcflurry-downloads-generation/models_class1_presentation/models
time mhcflurry-calibrate-percentile-ranks --models-dir /hpc/users/odonnt02/mhcflurry-scratch/20200609/mhcflurry-downloads-generation/models_class1_presentation/models --match-amino-acid-distribution-data "/hpc/users/odonnt02/.local/share/mhcflurry/4/1.7.0/models_class1_pan//models.combined/train_data.csv.bz2" --alleles-file "/hpc/users/odonnt02/.local/share/mhcflurry/4/1.7.0/models_class1_pan//models.combined/train_data.csv.bz2" --predictor-kind class1_presentation --num-peptides-per-length 10000 --alleles-per-genotype 1 --num-genotypes 50 --verbosity 1
